# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='\u8bed\u8a00'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u4e0a\u6b21\u767b\u5f55\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u6b21\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, verbose_name='\u624b\u673a\u53f7'),
            preserve_default=False,
        ),
    ]
