# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170216_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('edit_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9c\x80\xe8\xbf\x91\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('body', models.TextField(verbose_name=b'\xe8\xaf\x84\xe8\xae\xba\xe5\x86\x85\xe5\xae\xb9')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe6\x89\x80\xe5\xb1\x9eid')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('passward', models.CharField(max_length=30, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\xb3\xa8\xe5\x86\x8c\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_login_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe7\x99\xbb\xe5\xbd\x95\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe4\xb8\x8a\xe6\xac\xa1\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('icon_name', models.CharField(blank=True, help_text=b'\xe4\xb8\xba\xe7\xa9\xba\xe5\x88\x99\xe4\xb8\xba\xe9\xbb\x98\xe8\xae\xa4\xe5\xa4\xb4\xe5\x83\x8f', max_length=60, verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f\xe6\x96\x87\xe4\xbb\xb6\xe5\x90\x8d')),
                ('phone_number', models.CharField(max_length=11, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba\xe5\x8f\xb7')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1\xe5\x9c\xb0\xe5\x9d\x80')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7id'),
        ),
    ]
