# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170223_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85id'),
            preserve_default=False,
        ),
    ]
